name: Build Project

on:
  push:
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - .github/**
      - .gitignore
      - CHANGELOG.md
      - LICENSE
      - README.md
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: ReClass/packages.lock.json
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore -c Release -clp:NoSummary

      - name: Upload Build Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          path: bin/*
